### PR TITLE
Rebrand from ASI to Faculty

### PR DESCRIPTION
**Pull request by srstevenson**
`ai.faculty` needs registering on Sonatype in order to publish new releases.

### CODE REVIEW

**Comment by srstevenson** [comment]
Bump.

**Comment by tomas-milata** [comment]
@srstevenson I'm happy to help to push this through, but don't have access to our Sonatype account if it is a thing, or not exactly sure how it works.

**Comment by srstevenson** [comment]
We'll need to register the `ai.faculty` namespace on Sonatype, but we can push this PR through to master in the meantime.

**Comment by tomas-milata** [comment]
We should't merge this until we're able to publish releases, otherwise, releases of possible new hotfixes of master would be blocked.

**Comment by pbugnion** [comment]
Tomas and I opened a ticket with sonatype: https://issues.sonatype.org/browse/OSSRH-46996

**Comment by tomas-milata** [comment]
We finally managed to claim `ai.faculty` group ID on sonatype and releasing seems to work -- I tried snapshots and then did a real 0.3.2 release and tested it on one of our microservices, so this is good to be merged now.

Relevant sonatype support ticket: https://issues.sonatype.org/browse/OSSRH-50677

**Comment by tomas-milata** [comment]
Sorry, I always accidentally close PRs on github...

**Comment by tomas-milata** [comment]
There's a fix of the failing build in #36.

**Comment by srstevenson** [comment]
I rebased this on master now #36 is merged.

**Pull request merged**
